[server]
host = "127.0.0.1"
port = 5001

[data]
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"
delimiter = "|"
table_name = "movies"
sample_query = "SELECT * FROM {table_name} LIMIT 5"

[styles]
dataframe_css = "app/dataframe.css"